authors:
  odsbot:
    name: OpenDataSicilia Bot
    description: BOT
    avatar: https://cdn4.cdn-telegram.org/file/KP0sN_udqOjZ089vepl8nTt-B9SIpafLp-5Bw29R5ed7twQSCL3R0gXPuU0vodOYF8xPZSsWXr2T9UDCxNlZBMSUqaDHbTnNtOOLrEAVZ4xmaA_JafdOfK1swJx8KgFrL44taWRHWz79M5eRrvfIHspLW6EMf3pBMnt3qU3FKROIO4VH-drgfEXDDp33dFq8w7VSHSMEf3h6BRejfiJj2eSEXYZE6OgqZz6GJjqaeabzl490-P539Whs80qs3VkbQQEibwVrwicYlyHc2Mkmg_Pnq1pe8kcVq2v1W5F_xTkikslkSsjQmMoltU0FMMx5AifK4cDRJWBmYKALqniJLg.jpg