authors:
  odsbot:
    name: OpenDataSicilia Bot
    description: BOT
    avatar: https://raw.githubusercontent.com/opendatasicilia/emergenza-idrica-sicilia/refs/heads/main/risorse/imgs/logo-OpenDataSiciliaBot.png