name: Download and convert PDF

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name ODS[bot]
          git config user.email actions@users.noreply.github.com

      - name: Setup uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |-
          mkdir -p ~/bin
          cp bin/mlr ~/bin
          cd ~/bin
          chmod +x mlr
          sudo apt-get install jq
          uv pip install llm llm-gemini scrape-cli yq frictionless
  
      - name: Setup llm
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: |
          echo "$GEMINI_KEY" | llm keys set gemini

      - name: Download and convert data (volumi invasati) from PDF
        run: |
          export PATH=$PATH:~/bin
          chmod +x ./scripts/check_convert_volumi.sh
          ./scripts/check_convert_volumi.sh

      - name: Frictionless data validation
        run: frictionless validate datapackage.yaml

      - name: Send telegram message (new data)
        if: ${{ hashFiles('risorse/msgs/new_volumi.md') != '' }}
        env: 
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d parse_mode="Markdown" -d text="$(cat ./risorse/msgs/new_volumi.md)"
          rm ./risorse/msgs/new_volumi.md
          echo "Telegram message (new data [volumi]) sent"

      - name: Commit and push new data
        run: |-
          git add -A
          git commit -m "[volumi] Aggiornati i dati dei volumi invasati $(date --iso-8601)" || exit 0
          git push

      - name: Download and summarize PDF document (verbali)
        run: chmod +x ./scripts/check_convert_verbali.sh && ./scripts/check_convert_verbali.sh

        # questo secondo me deve essere gestito dal deploy di mkdocs e non da questa action
      - name: Send telegram message (new doc)
        if: ${{ hashFiles('risorse/msgs/new_verbale.md') != '' }}
        env: 
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d parse_mode="Markdown" -d text="$(cat ./risorse/msgs/new_verbale.md)"
          rm ./risorse/msgs/new_verbale.md
          echo "Telegram message sent"

      - name: Commit and push new doc
        run: |-
          git add -A
          git commit -m "[verbali] Creato nuovo blog post $(date --iso-8601)" || exit 0
          git push
