name: Download and convert PDF

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |-
          mkdir -p ~/bin
          cp bin/mlr ~/bin
          cd ~/bin
          chmod +x mlr
          sudo apt-get install jq
          uv pip install llm llm-gemini scrape-cli yq frictionless
  
      - name: Setup llm
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: |
          echo "$GEMINI_KEY" | llm keys set gemini

      - name: Download and convert PDF
        run: |
          export PATH=$PATH:~/bin
          chmod +x ./scripts/check_convert.sh
          ./scripts/check_convert.sh
      
      - name: Frictionless data validation
        run: frictionless validate datapackage.yaml

      - name: Commit and push
        run: |-
          git config user.name "estrattore-automatico"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601)
          git commit -m "Aggiornati i dati dei volumi invasati ${timestamp}" || exit 0
          git push
